/***************************************************************************//**
 * @file
 * @brief sl_sidewalk_device_backup.c
 *******************************************************************************
 * # License
 * <b>Copyright 2023 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 * Your use of this software is governed by the terms of
 * Silicon Labs Master Software License Agreement (MSLA)available at
 * www.silabs.com/about-us/legal/master-software-license-agreement.
 * This software contains Third Party Software licensed by Silicon Labs from
 * Amazon.com Services LLC and its affiliates and is governed by the sections
 * of the MSLA applicable to Third Party Software and the additional terms set
 * forth in amazon_sidewalk_license.txt.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *  claim that you wrote the original software. If you use this software
 *  in a product, an acknowledgment in the product documentation would be
 *  appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *  misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 ******************************************************************************/

// -----------------------------------------------------------------------------
//                                   Includes
// -----------------------------------------------------------------------------

#include <stdint.h>
#include <string.h>
#include <stdbool.h>

#include "nvm3_manager.h"
#include "sid_pal_mfg_store_ifc.h"
#include "sl_sidewalk_log_pal.h"
#include "app_assert.h"
#include "sli_sidewalk_device_backup_certificate_common.h" // to be generated by `generate_certificate_common_part` script
#include "sl_memory_manager.h"
#include "psa/crypto_types.h"

#if (defined(EFR32XG24) || defined(EFR32XG28))
#include "em_msc.h"
#include "sl_clock_manager.h"
#else
#include "sl_se_manager_util.h"
#endif

#ifdef TEST
extern uint32_t simUSERDATA[USERDATA_SIZE];
#define USERDATA_BASE_ADDRESS simUSERDATA
#else
#define USERDATA_BASE_ADDRESS USERDATA_BASE
#endif // TEST

#include "nvm3.h"

// -----------------------------------------------------------------------------
//                              Macros and Typedefs
// -----------------------------------------------------------------------------

#define OFFSET_MAGIC_NUMBER (0)
#define OFFSET_MFG_OBJ_START (OFFSET_MAGIC_NUMBER + 1)

#define READ_BUF_MAX_SIZE (256)

// New magic number is introduced to indicate the case when the backup is performed
// with the new backup structure. (PRIV_ED25519 and PRIV_P256R1 key ids are backuped from mfg store,
// and not restored from sli_sidewalk_device_backup_certificate_common.h)
#define MAGIC_NUMBER_OLD (0xCAFEBABE)
#define MAGIC_NUMBER_NEW (0xDEADBEEF)

#if defined(SV_ENABLED)
#define ITS_OBJ_RANGE_START (0x83100)
#define ITS_OBJ_RANGE_END (0x870FF)

#define WRAPPED_KEY_NVM3_KEY_START (ITS_OBJ_RANGE_START)

#define WRAPPED_KEY_CNT (2)
#define WRAPPED_KEY_LEN (128)

#define ITS_REC_CACHE_SIZE (50)
#define ITS_REC_NVM3_REPACK_HEADROOM (0)
#endif // SV_ENABLED

typedef struct {
  uint16_t key;
  uint8_t len;
  const uint8_t *val; // NULL if device specific common otherwise
} mfg_obj_t;

// -----------------------------------------------------------------------------
//                          Static Function Declarations
// -----------------------------------------------------------------------------

static void erase_user_data(void);
static void write_user_data(uint32_t offset, void *data, uint32_t data_len);
static void read_user_data(uint32_t offset, uint8_t *data, uint32_t data_len);
static bool is_magic_number_present(uint32_t *magic_number);
static bool is_apid_valid(void);
#if defined(SV_ENABLED)
static bool are_wrapped_keys_present(nvm3_ObjectKey_t *wrapped_keys, size_t wrapped_keys_size);
#endif // SV_ENABLED
static bool is_backup_needed(void);
static bool is_restore_needed(void);
static bool is_backup_possible(void);
static bool is_restore_possible(void);
static void backup_refresh(void);
static void perform_backup(void);
static void perform_restore(void);

// -----------------------------------------------------------------------------
//                                Global Variables
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
//                                Static Variables
// -----------------------------------------------------------------------------

static const mfg_obj_t MFG_OBJECT_TABLE[] = {
  { .key = SID_PAL_MFG_STORE_DEVID, .len = SID_PAL_MFG_STORE_DEVID_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_VERSION, .len = SID_PAL_MFG_STORE_VERSION_SIZE, .val = VERSION_VAL },
  { .key = SID_PAL_MFG_STORE_SERIAL_NUM, .len = SID_PAL_MFG_STORE_SERIAL_NUM_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_SMSN, .len = SID_PAL_MFG_STORE_SMSN_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_APP_PUB_ED25519, .len = SID_PAL_MFG_STORE_APP_PUB_ED25519_SIZE, .val = APP_PUB_ED25519_VAL },
  { .key = SID_PAL_MFG_STORE_DEVICE_PRIV_ED25519, .len = SID_PAL_MFG_STORE_DEVICE_PRIV_ED25519_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DEVICE_PUB_ED25519, .len = SID_PAL_MFG_STORE_DEVICE_PUB_ED25519_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DEVICE_PUB_ED25519_SIGNATURE, .len = SID_PAL_MFG_STORE_DEVICE_PUB_ED25519_SIGNATURE_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DEVICE_PRIV_P256R1, .len = SID_PAL_MFG_STORE_DEVICE_PRIV_P256R1_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DEVICE_PUB_P256R1, .len = SID_PAL_MFG_STORE_DEVICE_PUB_P256R1_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DEVICE_PUB_P256R1_SIGNATURE, .len = SID_PAL_MFG_STORE_DEVICE_PUB_P256R1_SIGNATURE_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DAK_PUB_ED25519, .len = SID_PAL_MFG_STORE_DAK_PUB_ED25519_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DAK_PUB_ED25519_SIGNATURE, .len = SID_PAL_MFG_STORE_DAK_PUB_ED25519_SIGNATURE_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DAK_ED25519_SERIAL, .len = SID_PAL_MFG_STORE_DAK_ED25519_SERIAL_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DAK_PUB_P256R1, .len = SID_PAL_MFG_STORE_DAK_PUB_P256R1_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DAK_PUB_P256R1_SIGNATURE, .len = SID_PAL_MFG_STORE_DAK_PUB_P256R1_SIGNATURE_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_DAK_P256R1_SERIAL, .len = SID_PAL_MFG_STORE_DAK_P256R1_SERIAL_SIZE, .val = NULL },
  { .key = SID_PAL_MFG_STORE_PRODUCT_PUB_ED25519, .len = SID_PAL_MFG_STORE_PRODUCT_PUB_ED25519_SIZE, .val = PRODUCT_PUB_ED25519_VAL },
  { .key = SID_PAL_MFG_STORE_PRODUCT_PUB_ED25519_SIGNATURE, .len = SID_PAL_MFG_STORE_PRODUCT_PUB_ED25519_SIGNATURE_SIZE, .val = PRODUCT_PUB_ED25519_SIGNATURE_VAL },
  { .key = SID_PAL_MFG_STORE_PRODUCT_ED25519_SERIAL, .len = SID_PAL_MFG_STORE_PRODUCT_ED25519_SERIAL_SIZE, .val = PRODUCT_ED25519_SERIAL_VAL },
  { .key = SID_PAL_MFG_STORE_PRODUCT_PUB_P256R1, .len = SID_PAL_MFG_STORE_PRODUCT_PUB_P256R1_SIZE, .val = PRODUCT_PUB_P256R1_VAL },
  { .key = SID_PAL_MFG_STORE_PRODUCT_PUB_P256R1_SIGNATURE, .len = SID_PAL_MFG_STORE_PRODUCT_PUB_P256R1_SIGNATURE_SIZE, .val = PRODUCT_PUB_P256R1_SIGNATURE_VAL },
  { .key = SID_PAL_MFG_STORE_PRODUCT_P256R1_SERIAL, .len = SID_PAL_MFG_STORE_PRODUCT_P256R1_SERIAL_SIZE, .val = PRODUCT_P256R1_SERIAL_VAL },
  { .key = SID_PAL_MFG_STORE_MAN_PUB_ED25519, .len = SID_PAL_MFG_STORE_MAN_PUB_ED25519_SIZE, .val = MAN_PUB_ED25519_VAL },
  { .key = SID_PAL_MFG_STORE_MAN_PUB_ED25519_SIGNATURE, .len = SID_PAL_MFG_STORE_MAN_PUB_ED25519_SIGNATURE_SIZE, .val = MAN_PUB_ED25519_SIGNATURE_VAL },
  { .key = SID_PAL_MFG_STORE_MAN_ED25519_SERIAL, .len = SID_PAL_MFG_STORE_MAN_ED25519_SERIAL_SIZE, .val = MAN_ED25519_SERIAL_VAL },
  { .key = SID_PAL_MFG_STORE_MAN_PUB_P256R1, .len = SID_PAL_MFG_STORE_MAN_PUB_P256R1_SIZE, .val = MAN_PUB_P256R1_VAL },
  { .key = SID_PAL_MFG_STORE_MAN_PUB_P256R1_SIGNATURE, .len = SID_PAL_MFG_STORE_MAN_PUB_P256R1_SIGNATURE_SIZE, .val = MAN_PUB_P256R1_SIGNATURE_VAL },
  { .key = SID_PAL_MFG_STORE_MAN_P256R1_SERIAL, .len = SID_PAL_MFG_STORE_MAN_P256R1_SERIAL_SIZE, .val = MAN_P256R1_SERIAL_VAL },
  { .key = SID_PAL_MFG_STORE_SW_PUB_ED25519, .len = SID_PAL_MFG_STORE_SW_PUB_ED25519_SIZE, .val = SW_PUB_ED25519_VAL },
  { .key = SID_PAL_MFG_STORE_SW_PUB_ED25519_SIGNATURE, .len = SID_PAL_MFG_STORE_SW_PUB_ED25519_SIGNATURE_SIZE, .val = SW_PUB_ED25519_SIGNATURE_VAL },
  { .key = SID_PAL_MFG_STORE_SW_ED25519_SERIAL, .len = SID_PAL_MFG_STORE_SW_ED25519_SERIAL_SIZE, .val = SW_ED25519_SERIAL_VAL },
  { .key = SID_PAL_MFG_STORE_SW_PUB_P256R1, .len = SID_PAL_MFG_STORE_SW_PUB_P256R1_SIZE, .val = SW_PUB_P256R1_VAL },
  { .key = SID_PAL_MFG_STORE_SW_PUB_P256R1_SIGNATURE, .len = SID_PAL_MFG_STORE_SW_PUB_P256R1_SIGNATURE_SIZE, .val = SW_PUB_P256R1_SIGNATURE_VAL },
  { .key = SID_PAL_MFG_STORE_SW_P256R1_SERIAL, .len = SID_PAL_MFG_STORE_SW_P256R1_SERIAL_SIZE, .val = SW_P256R1_SERIAL_VAL },
  { .key = SID_PAL_MFG_STORE_AMZN_PUB_ED25519, .len = SID_PAL_MFG_STORE_AMZN_PUB_ED25519_SIZE, .val = AMZN_PUB_ED25519_VAL },
  { .key = SID_PAL_MFG_STORE_AMZN_PUB_P256R1, .len = SID_PAL_MFG_STORE_AMZN_PUB_P256R1_SIZE, .val = AMZN_PUB_P256R1_VAL },
  { .key = SID_PAL_MFG_STORE_APID, .len = SID_PAL_MFG_STORE_APID_SIZE, .val = APID_VAL },
  { .key = SID_PAL_MFG_STORE_SL_NVM3_VERSION, .len = SID_PAL_MFG_STORE_SL_NVM3_VERSION_SIZE, .val = SL_NVM3_VERSION_VAL }
};

#if !(defined(EFR32XG24) || defined(EFR32XG28))
static sl_se_command_context_t cmd_ctx;
#endif

// -----------------------------------------------------------------------------
//                          Public Function Definitions
// -----------------------------------------------------------------------------

void sl_sidewalk_device_backup_handle_backup_restore(void)
{
  sid_pal_mfg_store_region_t mfg_store_region = { 0 };
  sid_pal_mfg_store_init(mfg_store_region);

  if (is_backup_needed() && is_backup_possible()) {
    perform_backup();
  }
  if (is_restore_needed() && is_restore_possible()) {
    perform_restore();
  }

  backup_refresh();

  SL_SID_LOG_PAL_INFO("pal backup: %s ok", __func__);
}

// -----------------------------------------------------------------------------
//                          Static Function Definitions
// -----------------------------------------------------------------------------

/***************************************************************************//**
 * @brief Erases @userdata region of the memory
 *****************************************************************************/
static void erase_user_data(void)
{
#if (defined(EFR32XG24) || defined(EFR32XG28))
  sl_status_t st  = sl_clock_manager_enable_bus_clock(SL_BUS_CLOCK_MSC);
  app_assert(st == SL_STATUS_OK, "pal backup: msc clock enable failed, st: %ld", st);
  MSC_Status_TypeDef ret = MSC_ErasePage((uint32_t *)USERDATA_BASE_ADDRESS);
  app_assert(ret == mscReturnOk, "pal backup: @userdata erase failed, ret: %d", ret);
#else
  sl_status_t ret = sl_se_erase_user_data(&cmd_ctx);
  app_assert(ret == SL_STATUS_OK, "pal backup: @userdata erase failed, ret: %ld", ret);
#endif
}

/***************************************************************************//**
 * @brief Writes data to the @userdata memory region
 *
 * @param offset Offset from `USERDATA_BASE` address (increments by four)
 * @param data Data to be written to the @userdata region (it shall contain
 * a number of bytes that is divisable by four)
 * @param data_len Number of actual bytes to be written (it must be divisable
 * by four)
 *****************************************************************************/
static void write_user_data(uint32_t offset, void *data, uint32_t data_len)
{
  app_assert(data_len % sizeof(uint32_t) == 0, "pal backup: @userdata write failed due to unaligned data, off: %.3ld, len: %.3ld", offset, data_len);
#if (defined(EFR32XG24) || defined(EFR32XG28))
  MSC_Init();
  MSC_Status_TypeDef ret = MSC_WriteWord(((uint32_t *)USERDATA_BASE_ADDRESS + offset), data, data_len);
  app_assert(ret == mscReturnOk, "pal backup: @userdata write failed, off: %.3ld, len: %.3ld, ret: %d", offset, data_len, ret);
  MSC_Deinit();
#else
  sl_status_t ret = sl_se_write_user_data(&cmd_ctx, (sizeof(uint32_t) * offset), data, data_len);
  app_assert(ret == SL_STATUS_OK, "pal backup: @userdata write failed, off: %.3ld, len: %.3ld, ret: %ld", offset, data_len, ret);
#endif
}

/***************************************************************************//**
 * @brief Reads data from the @userdata memory region
 *
 * @param offset Offset from `USERDATA_BASE` address (increments by four)
 * @param data Read data buffer
 * @param data_len Number of actual bytes to be read (it must be divisable
 * by four)
 *****************************************************************************/
static void read_user_data(uint32_t offset, uint8_t *data, uint32_t data_len)
{
  app_assert(data_len % sizeof(uint32_t) == 0, "pal backup: @userdata read failed due to unaligned data, off: %.3ld, len: %.3ld", offset, data_len);
  for (uint8_t i = 0; i < data_len; i++) {
    data[i] = *((uint8_t *)USERDATA_BASE_ADDRESS + (offset * sizeof(uint32_t)) + i);
  }
}

/***************************************************************************//**
 * @brief Checks if magic number is present or not
 *
 * @note Checks the value in @userdata's magic number location. It has to be
 * written at the end of the backup process. If it's not there, it means that
 * backup did not take place, the backup region (@userdata) is erased or it is
 * corrupted. This function can also be used to check if restore is possible or
 * not. If the magic number is not there, it means that there is no valid backup
 * to be restored. In this case, the device gets useless and the user should
 * contact customer support.
 * 
 * @param magic_number Pointer to return the magic number value.
 *                     It can be NULL if the value is not needed.
 *
 * @return True if magic number is present false otherwise
 *****************************************************************************/
static bool is_magic_number_present(uint32_t *magic_number)
{
  uint32_t value;
  read_user_data(OFFSET_MAGIC_NUMBER, (uint8_t *)&value, sizeof(value));
  if (magic_number != NULL) {
    *magic_number = value;
  }
  return (value == MAGIC_NUMBER_NEW || value == MAGIC_NUMBER_OLD);
}

/***************************************************************************//**
 * @brief Checks if APID is valid or not
 *
 * @note Checks if the APID value (which is common to all sidewalk device
 * instances) matches with the value that is supposed to be on the manufacturing
 * image. If not, there are three possibilities:
 *    1. there is no manufacturing image flashed
 *    2. wrong manufacturing image flashed
 *    3. wrong common sidewalk device certificate added to the project
 *
 * @note Objects other than APID which are also common to all sidewalk device
 * instances could also have been used for checking. APID is arbitrarily chosen
 * among all common objects.
 *
 * @return True if APID is valid false otherwise
 *****************************************************************************/
static bool is_apid_valid(void)
{
  uint8_t apid_dev[SID_PAL_MFG_STORE_APID_SIZE];
  sid_pal_mfg_store_read(SID_PAL_MFG_STORE_APID, apid_dev, SID_PAL_MFG_STORE_APID_SIZE);
  return memcmp(apid_dev, APID_VAL, SID_PAL_MFG_STORE_APID_SIZE) == 0;
}

#if defined(SV_ENABLED)
/***************************************************************************//**
 * @brief Checks if wrapped keys are present or not
 *
 * @note There must be WRAPPED_KEY_CNT wrapped keys in the default NVM3
 * instance.
 * 
 * @param wrapped_keys  Pointer to the buffer where the found wrapped keys are stored.
 *                      If NULL, the function only checks if the keys are present without storing them.
 * @param wrapped_keys_size Size of the wrapped_keys buffer. It must be equal to WRAPPED_KEY_CNT.
 *
 * @return True if wrapped keys are present false otherwise
 *****************************************************************************/
static bool are_wrapped_keys_present(nvm3_ObjectKey_t *wrapped_keys, size_t wrapped_keys_size)
{
  Ecode_t st;
  uint32_t obj_type;
  size_t obj_len;
  uint8_t rec_cnt = 0;
  uint32_t crpyto_obj_num;
  nvm3_ObjectKey_t *crpyto_obj_keys = NULL;

  if(wrapped_keys != NULL && wrapped_keys_size != WRAPPED_KEY_CNT) {
    SL_SID_LOG_PAL_ERROR("pal backup: invalid wrapped keys buffer size");
    return false;
  }

  // Get all object keys in the platform crypto range, where the wrapped keys are stored.
  crpyto_obj_num = nvm3_enumObjects(nvm3_defaultHandle, NULL, 0, ITS_OBJ_RANGE_START, ITS_OBJ_RANGE_END);
  crpyto_obj_keys = (nvm3_ObjectKey_t *)sl_calloc(crpyto_obj_num, sizeof(nvm3_ObjectKey_t));
  if (!crpyto_obj_keys) {
    SL_SID_LOG_PAL_ERROR("pal backup: %s memory allocation failed", __func__);
    return false;
  }
  nvm3_enumObjects(nvm3_defaultHandle, crpyto_obj_keys, crpyto_obj_num, ITS_OBJ_RANGE_START, ITS_OBJ_RANGE_END);

  // Count all possible wrapped keys based on object type and length.
  for (uint32_t i = 0; i < crpyto_obj_num; i++) {
    st = nvm3_getObjectInfo(nvm3_defaultHandle, crpyto_obj_keys[i], &obj_type, &obj_len);
    if (st == ECODE_NVM3_OK && obj_type == NVM3_OBJECTTYPE_DATA && obj_len == WRAPPED_KEY_LEN) {
      if(rec_cnt < wrapped_keys_size && wrapped_keys != NULL) {
        // If the wrapped keys buffer is provided, copy the found key to it.
        wrapped_keys[rec_cnt] = crpyto_obj_keys[i];
      }
      rec_cnt++;
    }
  }

  sl_free(crpyto_obj_keys);
  crpyto_obj_keys = NULL;
  return (rec_cnt == WRAPPED_KEY_CNT); // Check if exactly the expected amount of key objects has been found
}
#endif // SV_ENABLED

/***************************************************************************//**
 * @brief Checks if backup is needed or not
 *
 * @return True if backup is needed false otherwise
 *****************************************************************************/
static bool is_backup_needed(void)
{
  bool needed = !is_magic_number_present(NULL);
  if (needed) {
    SL_SID_LOG_PAL_INFO("pal backup: backup needed");
  } else {
    SL_SID_LOG_PAL_INFO("pal backup: backup not needed");
  }
  return needed;
}

/***************************************************************************//**
 * @brief Checks if restore is needed or not
 *
 * @return True if restore is needed false otherwise
 *****************************************************************************/
static bool is_restore_needed(void)
{
#if defined(SV_ENABLED)
  bool needed = (!is_apid_valid() || !are_wrapped_keys_present(NULL, 0));
#else
  bool needed = !is_apid_valid();
#endif // SV_ENABLED
  if (needed) {
    SL_SID_LOG_PAL_INFO("pal backup: restore needed");
  } else {
    SL_SID_LOG_PAL_INFO("pal backup: restore not needed");
  }
  return needed;
}

/***************************************************************************//**
 * @brief Checks if backup is possible or not
 *
 * @return True if backup is possible false otherwise
 *****************************************************************************/
static bool is_backup_possible(void)
{
  bool ret = false;
#if defined(SV_ENABLED)
  ret = are_wrapped_keys_present(NULL, 0);
  app_assert(ret == true, "pal backup: device not provisioned yet");
#endif // SV_ENABLED
  ret = is_apid_valid();
  app_assert(ret == true, "pal backup: static cert not matching with mfg info");
  SL_SID_LOG_PAL_INFO("pal backup: backup possible");
  return true;
}

/***************************************************************************//**
 * @brief Checks if restore is possible or not
 *
 * @return True if restore is possible false otherwise
 *****************************************************************************/
static bool is_restore_possible(void)
{
  bool possible = is_magic_number_present(NULL);
  if (possible) {
    SL_SID_LOG_PAL_INFO("pal backup: restore possible");
  }
  app_assert(possible == true, "pal backup: restore not possible");
  return possible;
}

/***************************************************************************//**
 * @brief Refreshes the backup data if the magic number is old
 *
 * @note This function overwrites the backup data with the new structure
 *****************************************************************************/
static void backup_refresh(void)
{
  uint32_t magic_number;
  if (is_magic_number_present(&magic_number) && (magic_number == MAGIC_NUMBER_OLD)) {
    // If the backup was performed with the old structure, overwrite it with the new structure
    SL_SID_LOG_PAL_INFO("pal backup: old backup structure detected, overwriting with new structure");
    perform_backup();
  } 

}

/***************************************************************************//**
 * @brief Backups device data to @userdata region of the flash memory
 *
 * @note Magic number is written at the end of the backup process as an indicator
 * that can be checked at boot time to know if the device data has been backpuped
 * before or not.
 *
 * @note If device data is backuped once, there is no need to run this function
 * each boot. This can be checked by `is_backup_needed`.
 *****************************************************************************/
static void perform_backup(void)
{
  SL_SID_LOG_PAL_INFO("pal backup: backup started");

  uint8_t read_buffer[READ_BUF_MAX_SIZE];
  uint32_t offset = OFFSET_MFG_OBJ_START;
  uint32_t magic_number = MAGIC_NUMBER_NEW;
#if defined(SV_ENABLED)
  Ecode_t st;
  size_t obj_len;
  nvm3_ObjectKey_t wrapped_keys[WRAPPED_KEY_CNT];
#endif // SV_ENABLED

  erase_user_data();
  SL_SID_LOG_PAL_INFO("pal backup: @userdata erased");

  for (uint8_t i = 0; i < sizeof(MFG_OBJECT_TABLE) / sizeof(mfg_obj_t); i++) {
    if (MFG_OBJECT_TABLE[i].val == NULL) {
      // Backup device specific objects as the static data is hardcoded
      memset(read_buffer, 0, sizeof(read_buffer));
      sid_pal_mfg_store_read(MFG_OBJECT_TABLE[i].key, read_buffer, MFG_OBJECT_TABLE[i].len);
      uint32_t len = MFG_OBJECT_TABLE[i].len;

      #if defined(SV_ENABLED)
      if(MFG_OBJECT_TABLE[i].key == SID_PAL_MFG_STORE_DEVICE_PRIV_ED25519 ||
         MFG_OBJECT_TABLE[i].key == SID_PAL_MFG_STORE_DEVICE_PRIV_P256R1) {
        // In case of secure vault, only the first 4 bytes (key id) are relevant
        len = sizeof(psa_key_id_t);
      }
      #endif // SV_ENABLED

      if (len % sizeof(uint32_t) != 0) {
        // unaligned data: align the length to the next word boundary
        len = MFG_OBJECT_TABLE[i].len + (sizeof(uint32_t) - (MFG_OBJECT_TABLE[i].len % sizeof(uint32_t)));
      }
      write_user_data(offset, read_buffer, len);
      SL_SID_LOG_PAL_INFO("pal backup: mfg obj written to @userdata, key: 0x%.5lx, off: %.3ld, len: %.3ld", MFG_OBJECT_TABLE[i].key, offset, len);
      offset += len / sizeof(uint32_t);
    }
  }

#if defined(SV_ENABLED)
  if (are_wrapped_keys_present(wrapped_keys, WRAPPED_KEY_CNT) != true) {
    app_assert(false, "pal backup: wrapped keys not found in default NVM3 instance");
  }
  for (uint32_t i = 0; i < WRAPPED_KEY_CNT; i++) {
    uint32_t key = wrapped_keys[i];
    obj_len = WRAPPED_KEY_LEN; // We know this from the are_wrapped_keys_present() call
    // Backup wrapped keys
    memset(read_buffer, 0, sizeof(read_buffer));
    st = nvm3_readData(nvm3_defaultHandle, key, read_buffer, obj_len);
    app_assert(st == ECODE_NVM3_OK, "pal backup: default NVM3 object cannot be read, key: 0x%.5lx", key);
    uint32_t len = 0;
    if (obj_len % sizeof(uint32_t) == 0) {
      // aligned data
      len = (uint32_t)obj_len;
    } else {
      // unaligned data: align the length to the next word boundary
      len = obj_len + (sizeof(uint32_t) - (obj_len % sizeof(uint32_t)));
    }
    // keys are stored with the following format: | nvm3 key (4 bytes) | wrapped key (120 bytes) |
    write_user_data(offset, (void *)&key, sizeof(uint32_t));
    offset += (sizeof(uint32_t) / sizeof(uint32_t));
    write_user_data(offset, read_buffer, len);
    SL_SID_LOG_PAL_INFO("pal backup: wrp key written to @userdata, key: 0x%.5lx, off: %.3ld, len: %.3ld", key, offset, len);
    offset += len / sizeof(uint32_t);
  }
#endif // SV_ENABLED

  write_user_data(OFFSET_MAGIC_NUMBER, (void *)&magic_number, sizeof(magic_number));
  SL_SID_LOG_PAL_INFO("pal backup: backup completed with %ld bytes written to @userdata", (offset * sizeof(uint32_t)));
}

/***************************************************************************//**
 * @brief Restores device data from @userdata region of the flash memory
 *
 * @note If device data is restored once, there is no need to run this function
 * each boot. This can be checked by `is_restore_needed`.
 *****************************************************************************/
static void perform_restore(void)
{
  SL_SID_LOG_PAL_INFO("pal backup: restore started");

  uint8_t read_buffer[READ_BUF_MAX_SIZE];
  int32_t ret;
  uint32_t offset = OFFSET_MFG_OBJ_START;
  Ecode_t st;
  uint16_t bytes_written_sta_obj = 0;
  uint32_t magic_number;
  bool old_magic_number;

  if (!is_magic_number_present(&magic_number)) {
    app_assert(false, "pal backup: magic number not present, restore not possible");
  }
  // If the magic number is old, it means that the backup was performed with the old structure
  old_magic_number = (magic_number == MAGIC_NUMBER_OLD);

  st = nvm3_eraseAll(nvm3_defaultHandle);
  app_assert(st == ECODE_NVM3_OK, "pal backup: default NVM3 inst cannot be erased, st: %ld", st);
  SL_SID_LOG_PAL_INFO("pal backup: default NVM3 inst erased");

  for (uint8_t i = 0; i < sizeof(MFG_OBJECT_TABLE) / sizeof(mfg_obj_t); i++) {
    #if defined(SV_ENABLED)
      // In the old structure, the private key ids were not saved to userdata during backup
      bool restore_old_priv_key =  old_magic_number &&
                    (MFG_OBJECT_TABLE[i].key == SID_PAL_MFG_STORE_DEVICE_PRIV_ED25519 ||
                     MFG_OBJECT_TABLE[i].key == SID_PAL_MFG_STORE_DEVICE_PRIV_P256R1);
    #else
      // If secure vault is not used, the private keys are always backuped in userdata
      bool restore_old_priv_key = false;
    #endif
    if (!restore_old_priv_key && MFG_OBJECT_TABLE[i].val == NULL) {
      // device specific data
      memset(read_buffer, 0, sizeof(read_buffer));
      uint32_t len = MFG_OBJECT_TABLE[i].len;

      #if defined(SV_ENABLED)
      if(MFG_OBJECT_TABLE[i].key == SID_PAL_MFG_STORE_DEVICE_PRIV_ED25519 ||
         MFG_OBJECT_TABLE[i].key == SID_PAL_MFG_STORE_DEVICE_PRIV_P256R1) {
        // Only the first 4 bytes (key id) are relevant in case of secure vault
        len = sizeof(psa_key_id_t);
      }
      #endif // SV_ENABLED

      if (len % sizeof(uint32_t) != 0) {
        // unaligned data: align the length to the next word boundary
        len = MFG_OBJECT_TABLE[i].len + (sizeof(uint32_t) - (MFG_OBJECT_TABLE[i].len % sizeof(uint32_t)));
      }
      read_user_data(offset, read_buffer, len);
      ret = sid_pal_mfg_store_write(MFG_OBJECT_TABLE[i].key, read_buffer, MFG_OBJECT_TABLE[i].len);
      SL_SID_LOG_PAL_INFO("pal backup: dyn obj written to default NVM3 inst, key: 0x%.5lx, len: %.3ld", MFG_OBJECT_TABLE[i].key, MFG_OBJECT_TABLE[i].len);
      offset += len / sizeof(uint32_t);
    } else {
      // common data
      if( MFG_OBJECT_TABLE[i].key == SID_PAL_MFG_STORE_DEVICE_PRIV_ED25519) {
        // Restore private key id from the common part, as private key ids are not stored in the userdata region in the old structure
        ret = sid_pal_mfg_store_write(MFG_OBJECT_TABLE[i].key, DEVICE_PRIV_ED25519, MFG_OBJECT_TABLE[i].len);
      }
      else if( MFG_OBJECT_TABLE[i].key == SID_PAL_MFG_STORE_DEVICE_PRIV_P256R1) {
        // Restore private key id from the common part, as private key ids are not stored in the userdata region in the old structure
        ret = sid_pal_mfg_store_write(MFG_OBJECT_TABLE[i].key, DEVICE_PRIV_P256R1, MFG_OBJECT_TABLE[i].len);
      }
      else {
        ret = sid_pal_mfg_store_write(MFG_OBJECT_TABLE[i].key, MFG_OBJECT_TABLE[i].val, MFG_OBJECT_TABLE[i].len);
      }
      SL_SID_LOG_PAL_INFO("pal backup: sta obj written to default NVM3 inst, key: 0x%.5lx, len: %.3ld", MFG_OBJECT_TABLE[i].key, MFG_OBJECT_TABLE[i].len);
      bytes_written_sta_obj += MFG_OBJECT_TABLE[i].len;
    }
    app_assert(ret == 0, "pal backup: obj cannot be written, key: 0x%.5x, ret: %ld", MFG_OBJECT_TABLE[i].key, ret);
  }

#if defined(SV_ENABLED)
  for (uint8_t i = 0; i < WRAPPED_KEY_CNT; i++) {
    // wrapped keys
    uint32_t key = 0;
    read_user_data(offset, (void *)&key, sizeof(uint32_t));
    offset += (sizeof(uint32_t) / sizeof(uint32_t));
    memset(read_buffer, 0, sizeof(read_buffer));
    read_user_data(offset, read_buffer, WRAPPED_KEY_LEN);
    st = nvm3_writeData(nvm3_defaultHandle, (nvm3_ObjectKey_t)key, read_buffer, WRAPPED_KEY_LEN);
    app_assert(st == ECODE_NVM3_OK, "pal backup: obj cannot be written, key: 0x%.5lx, len: %.3d, st: %ld", key, WRAPPED_KEY_LEN, st);
    if (nvm3_repackNeeded(nvm3_defaultHandle)) {
      st = nvm3_repack(nvm3_defaultHandle);
      app_assert(st == ECODE_NVM3_OK, "pal backup: default NVM3 inst repack failed, key: 0x%.5lx, len: %.3d, st: %ld", key, WRAPPED_KEY_LEN, st);
    }
    SL_SID_LOG_PAL_INFO("pal backup: wrp key written to default NVM3 inst, key: 0x%.5lx, len: %.3d", key, WRAPPED_KEY_LEN);
    offset += WRAPPED_KEY_LEN / sizeof(uint32_t);
  }
#endif // SV_ENABLED

  SL_SID_LOG_PAL_INFO("pal backup: restore completed with %ld bytes written to default NVM3 inst", (offset * sizeof(uint32_t)) + bytes_written_sta_obj);
}
